/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/**
 * @file	FSPDFObjC.h
 * @brief	This file contains definitions of object-c APIs for Foxit PDF SDK.
 */

#import <Foundation/Foundation.h>

#ifdef __cplusplus
extern "C" {
#endif

#import "FSCommon.h"
#import "FSFDF.h"
#import "FSAction.h"
#import "FSRender.h"
#import "FSPDFDoc.h"
#import "FSPDFForm.h"
#import "FSPDFGraphicsObject.h"
#import "FSPDFObject.h"
#import "FSPDFText.h"
#import "FSPDFSecurity.h"
#import "FSPDFSignature.h"
#import "FSPDFReflow.h"
#import "FSPressureSenseInk.h"
#import "FSPDFLayer.h"
#import "FSFullTextSearch.h"
    
#ifdef __cplusplus
}
#endif

